# Generated by Django 5.2.12 on 2026-03-25 04:50

import api.models.classroom
import api.models.communications
import api.models.school
import api.models.staff
import api.models.student
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_exammodel_resultmodel'), ('api', '0003_rename_author_notice_school_and_more'), ('api', '0004_alter_exammodel_id_alter_resultmodel_id'), ('api', '0005_alter_staffmodel_date_of_birth_and_more'), ('api', '0006_studentmodel_parent_account_no_and_more'), ('api', '0007_attachment_attchtype'), ('api', '0008_rename_attchtype_attachment_attachtype_and_more'), ('api', '0009_classroommodel_teachers'), ('api', '0010_alter_classroommodel_teachers'), ('api', '0011_timetablemodel'), ('api', '0012_staffattendance_syllabusmodel_and_more'), ('api', '0013_alter_timetablemodel_day'), ('api', '0014_alter_syllabusmodel_options_and_more'), ('api', '0015_otpmodel_sessionmodel_exammodel_description_and_more'), ('api', '0016_alter_blacklistedtoken_unique_together_and_more'), ('api', '0017_alter_schoolmodel_options_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='ClassroomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['class_name', 'section_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school_name', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,13}$')])),
                ('school_address', models.CharField(max_length=100)),
                ('school_city', models.CharField(max_length=100)),
                ('school_state', models.CharField(max_length=100)),
                ('school_zipcode', models.CharField(max_length=100)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to=api.models.school.school_logo_upload)),
                ('school_logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('school_website', models.URLField(blank=True, null=True)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('staff_limit', models.CharField(default="25", max_length=10)),
                ('student_limit', models.CharField(default="500", max_length=10)),
                ('school_affNo', models.CharField(default='1', max_length=30)),
                ('school_board', models.CharField(choices=[('ICSE', 'ICSE'), ('CBSE', 'CBSE'), ('HPBOSE', 'HPBOSE')], default='CBSE', max_length=7)),
                ('school_head', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, upload_to=api.models.staff.staff_profile_upload)),
                ('profile_pic_url', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1)),
                ('mobile_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,13}$')])),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('date_of_joining', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('ifsc_code', models.CharField(default='12345678', max_length=50)),
                ('is_teaching_staff', models.BooleanField(default=True)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['date_of_joining', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject_pic', models.ImageField(blank=True, upload_to=api.models.classroom.subject_profile_upload)),
                ('subject_pic_url', models.CharField(blank=True, max_length=500, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroommodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_by', to='api.staffmodel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'unique_together': set(),
            },
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staffmodel'),
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel'),
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='sub_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_class_teacher', to='api.staffmodel'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FileField(blank=True, null=True, upload_to=api.models.communications.notice_attach_upload)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('attachType', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classroommodel',
            unique_together={('class_name', 'section_name', 'school')},
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers_of_class', to='api.staffmodel'),
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hashed_otp', models.CharField(max_length=128)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='classroommodel',
            name='section_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ThoughtDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommonTimeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=128)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commontime', to='api.classroommodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classroommodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classroommodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_marks', models.IntegerField(default=100)),
                ('tag', models.CharField(max_length=50)),
                ('date_of_exam', models.DateField()),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroommodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'ordering': ['-date_of_exam'],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='FeesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroommodel')),
                ('fee_type', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=api.models.student.student_profile_upload)),
                ('profile_pic_url', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1)),
                ('address', models.TextField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,13}$')])),
                ('date_of_admission', models.DateField()),
                ('roll_no', models.CharField(max_length=20)),
                ('admission_no', models.CharField(max_length=35)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classroommodel', verbose_name='Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('subjects', models.ManyToManyField(blank=True, related_name='learning_subjects', to='api.subject')),
                ('parent_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('waiver_percent', models.DecimalField(decimal_places=5, default=Decimal('0.0'), max_digits=10)),
                ('waiver_type', models.CharField(default='none', max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'ordering': ['roll_no'],
                'unique_together': set(),
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimeTableModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='api.classroommodel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staffmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classroommodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staffmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('read_by_staff', models.ManyToManyField(blank=True, related_name='read_by_teachers', to='api.staffmodel')),
                ('read_by_students', models.ManyToManyField(blank=True, related_name='read_by_students', to='api.studentmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'ordering': ['-date_posted'],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('1', 'Cheque'), ('2', 'Cash at Counter'), ('3', 'Net Banking'), ('4', 'Demand Draft')], max_length=1)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feesdetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmodel')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exammodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmodel')),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'ordering': ['-exam__date_of_exam'],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('present', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staffmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'verbose_name': 'StaffAttendance',
                'verbose_name_plural': 'StaffAttendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['staff', 'date'], name='api_staffat_staff_i_daa113_idx')],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='StaffYearAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('attendance_data', models.JSONField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staffmodel')),
            ],
            options={
                'verbose_name': 'StaffYearAttendance',
                'verbose_name_plural': 'StaffYearAttendance',
                'indexes': [models.Index(fields=['staff', 'year'], name='api_staffye_staff_i_db1b2e_idx')],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('present', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroommodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'verbose_name': 'StudentAttendance',
                'verbose_name_plural': 'StudentAttendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'date'], name='api_student_student_37c5a6_idx')],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='StudentYearAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('attendance_data', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmodel')),
            ],
            options={
                'verbose_name': 'StudentYearAttendance',
                'verbose_name_plural': 'StudentYearAttendance',
                'indexes': [models.Index(fields=['student', 'year'], name='api_student_student_b923e8_idx')],
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='SyllabusModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroommodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessionmodel')),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': set(),
                'constraints': [models.UniqueConstraint(fields=('token', 'user'), name='unique_token_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='classroommodel',
            constraint=models.UniqueConstraint(fields=('class_name', 'section_name', 'school', 'session'), name='unique_classroom_per_school_session'),
        ),
        migrations.AddConstraint(
            model_name='eventmodel',
            constraint=models.UniqueConstraint(fields=('school', 'date', 'title'), name='unique_event_per_school_date_title'),
        ),
        migrations.AddConstraint(
            model_name='exammodel',
            constraint=models.UniqueConstraint(fields=('school', 'classroom', 'subject', 'date_of_exam'), name='unique_exam_per_school_class_subject_date'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('school', 'title', 'date_posted'), name='unique_notice_per_school'),
        ),
        migrations.AddConstraint(
            model_name='paymentinfo',
            constraint=models.UniqueConstraint(fields=('student', 'fees'), name='unique_payment_per_student_fees'),
        ),
        migrations.AddConstraint(
            model_name='resultmodel',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'session'), name='unique_result_per_student_exam_session'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_attendance_per_date'),
        ),
        migrations.AddConstraint(
            model_name='staffmodel',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'mobile_number', 'school', 'session'), name='unique_staff_per_school_session'),
        ),
        migrations.AddConstraint(
            model_name='staffyearattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'year'), name='unique_staff_year_attendance'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_date'),
        ),
        migrations.AddConstraint(
            model_name='studentmodel',
            constraint=models.UniqueConstraint(fields=('school', 'roll_no', 'admission_no', 'classroom', 'session'), name='unique_student_per_school_session'),
        ),
        migrations.AddConstraint(
            model_name='studentyearattendance',
            constraint=models.UniqueConstraint(fields=('student', 'year'), name='unique_student_year_attendance'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'classroom', 'session'), name='unique_subject_per_classroom_session'),
        ),
        migrations.AddConstraint(
            model_name='syllabusmodel',
            constraint=models.UniqueConstraint(fields=('school', 'classroom', 'subject', 'session'), name='unique_syllabus_per_school_class_subject_session'),
        ),
        migrations.AlterModelOptions(
            name='schoolmodel',
            options={'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='staff_limit',
            field=models.CharField(default='25', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='student_limit',
            field=models.CharField(default='500', max_length=10),
        ),
    ]
