# Generated by Django 4.0.4 on 2023-02-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField(default=100)),
                ('tag', models.CharField(max_length=50)),
                ('date_of_exam', models.DateField()),
                ('attachments', models.ManyToManyField(blank=True, to='api.attachment')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroommodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'ordering': ['-date_of_exam'],
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exammodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentmodel')),
            ],
            options={
                'ordering': ['-exam__date_of_exam'],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
