# Generated by Django 4.0.4 on 2023-02-04 19:39

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=1)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staffmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
            ],
            options={
                'ordering': ['class_name', 'section_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(blank=True, upload_to=api.models.student_profile_upload)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1)),
                ('address', models.TextField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,13}$')])),
                ('date_of_admission', models.DateField()),
                ('roll_no', models.CharField(max_length=20)),
                ('admission_no', models.CharField(max_length=35)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classmodel', verbose_name='Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
            ],
            options={
                'ordering': ['roll_no'],
                'unique_together': {('school', 'roll_no')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject_pic', models.ImageField(blank=True, upload_to=api.models.subject_profile_upload)),
                ('classroom', models.ManyToManyField(related_name='class_map', to='api.classmodel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schoolmodel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
