# Generated by Django 4.0.4 on 2023-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='school_website',
            field=models.URLField(null=True),
        ),
    ]
