# Generated by Django 4.0.4 on 2023-02-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staffmodel_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommodel',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staffmodel'),
        ),
        migrations.AlterField(
            model_name='classroommodel',
            name='sub_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_class_teacher', to='api.staffmodel'),
        ),
    ]
