# Generated by Django 4.0.4 on 2023-02-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='sub_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_class_teacher', to='api.staffmodel'),
        ),
    ]
