# Generated by Django 4.0.4 on 2023-02-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_classroommodel_class_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='className',
            new_name='classroom',
        ),
        migrations.AlterUniqueTogether(
            name='studentmodel',
            unique_together={('school', 'roll_no', 'admission_no', 'classroom')},
        ),
    ]
