# Generated by Django 4.0.4 on 2023-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_classroommodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
