# Generated by Django 4.0.4 on 2023-02-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exammodel_id_alter_resultmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
