# Generated by Django 4.0.4 on 2023-02-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classmodel_sub_class_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassModel',
            new_name='ClassroomModel',
        ),
    ]
