# Generated by Django 4.0.4 on 2023-02-07 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_staffmodel_is_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_class_teacher': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_by', to='api.staffmodel'),
        ),
    ]
