# Generated by Django 4.0.4 on 2023-02-07 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_subject_created_at_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
