# Generated by Django 4.0.4 on 2023-02-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_staffmodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='parent_account_no',
            field=models.CharField(default='23456789', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='date_of_joining',
            field=models.DateField(),
        ),
    ]
