# Generated by Django 4.0.4 on 2023-02-07 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommodel',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'is_class_teacher': False}, on_delete=django.db.models.deletion.CASCADE, to='api.staffmodel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_by', to='api.staffmodel'),
        ),
    ]
