# Generated by Django 4.0.4 on 2023-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentmodel_parent_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attchType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
