# Generated by Django 4.0.4 on 2023-02-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_classroommodel_class_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmodel',
            unique_together={('school', 'roll_no', 'admission_no', 'className')},
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='subjects',
            field=models.ManyToManyField(related_name='learning_subjects', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='date_of_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='school_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
