# Generated by Django 4.0.4 on 2023-02-08 13:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_studentmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.student_profile_upload),
        ),
    ]
