# Generated by Django 4.0.4 on 2023-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_studentmodel_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmodel',
            name='staff_limit',
            field=models.CharField(default=25, max_length=10),
        ),
        migrations.AddField(
            model_name='schoolmodel',
            name='student_limit',
            field=models.CharField(default=500, max_length=10),
        ),
    ]
