# Generated by Django 4.0.4 on 2023-03-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_staffattendance_syllabusmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablemodel',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10),
        ),
    ]
