# Generated by Django 4.0.4 on 2023-03-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_timetablemodel_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabusmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='timetablemodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabusmodel',
            unique_together={('school', 'classroom', 'subject')},
        ),
        migrations.RemoveField(
            model_name='syllabusmodel',
            name='date_of_exam',
        ),
    ]
