# Generated by Django 5.2.12 on 2026-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0017_alter_schoolmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
