# Generated by Django 5.2.12 on 2026-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_paymentinfo_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
